[project]
name = "001"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "arviz>=0.21.0",
    "marimo>=0.13.15",
    "polars>=1.30.0",
    "pymc>=5.23.0",
    "ruff>=0.12.0",
]
